name: SQLite CI

on:
  push:
    branches:
      - master

jobs:
  test-db:
    runs-on: ubuntu-latest

    steps:
      - name: Projekt herunterladen
        uses: actions/checkout@v4

      - name: SQLite installieren
        run: sudo apt-get update && sudo apt-get install -y sqlite3

      - name: Datenbank erstellen
 	 run: |
    	  rm -f bibliothek.db
          sqlite3 bibliothek.db < ./schema.sql
          sqlite3 bibliothek.db < ./data.sql

      - name: Row Counts prüfen
         run: |
          sqlite3 bibliothek.db "
          SELECT 'buch', COUNT(*) FROM buch
          UNION ALL
          SELECT 'exemplar', COUNT(*) FROM exemplar
          UNION ALL
          SELECT 'mitglied', COUNT(*) FROM mitglied
          UNION ALL
          SELECT 'ausleihe', COUNT(*) FROM ausleihe;
          "
